# Categories
@baseUrl = http://localhost:3000/api

# @name getAllCategories
GET {{baseUrl}}/categories

###

# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "Iphone X2"
}

###

# @name updateCategory
PATCH {{baseUrl}}/categories/3
Content-Type: application/json

{
    "name": "Iphone 13"
}

###

# @name deleteCategory
DELETE {{baseUrl}}/categories/2