# Products
@baseUrl=http://localhost:3000/api
@resourceName=products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###
# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?color=maroon&price_gte=200

###
# @name filterProductsLike
GET {{baseUrl}}/{{resourceName}}?name_like=tasty

###
# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=2

###
# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

###
# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "categoryId": "757df16a-96c9-40e8-87af-f8bc4bab2e2d",
    "name": "Test",
    "color": "Red",
    "price": 666,
    "description": "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
    "thumbnailUrl": "http://placeimg.com/400/400"
}

###
# @name update
PATCH {{baseUrl}}/{{resourceName}}/IjrIDTV
Content-Type: application/json

{
    "categoryId": "757df16a-96c9-40e8-87af-f8bc4bab2e2d",
    "name": "Test",
    "color": "Red",
    "price": 999,
}

###
# @name delete
DELETE {{baseUrl}}/{{resourceName}}/2